version: '3.3'

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    restart: unless-stopped
  redis:
    image: redis:alpine
    container_name: redis-gympoint
    command: redis-server 
    ports:
      - "6379:6379"

